alias: Notify trash paper
trigger:
  platform: state
  entity_id: sensor.trash_vandaag
  to: papier
action:
  service: notify.notify
  data:
    title: Afval
    message: Vandaag wordt papier opgehaald