alias: Notify trash paper
trigger:
  platform: state
  entity_id: sensor.trash_vandaag
  to: 'papier'
  for: "07:00:00"
action:
  service: notify.mobile_app_oneplus_a5010
  data:
    message: "Vandaag wordt papier opgehaald"