alias: Notify trash pmd
trigger:
  platform: state
  entity_id: sensor.trash_vandaag
  to: 'pmd'
  for: "07:00:00"
action:
  service: notify.mobile_app_oneplus_a5010
  data:
    message: "Vandaag wordt plastic opgehaald"