# Turn off bathroom floor heater
alias: Badkamer vloerverwarming uit
trigger:
  - platform: time
    at: '08:30:00'
  - platform: time
    at: '23:00:00'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.bathroom_thermostat
      temperature: 12
  # delay a bit, same timing does not work
  - delay: '00:00:03'
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.bathroom_thermostat
      hvac_mode: 'off'
