# Turn on bathroom floor heater
alias: Badkamer vloerverwarming aan
trigger:
  - platform: time
    at: '06:00:00'
  - platform: time
    at: '20:00:00'
action:
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.thermofloor_as_heatit_thermostat_tf_056_mode
      hvac_mode: 'heat'
  # delay a bit, same timing does not work
  - delay: '00:00:03'
  - service: climate.set_temperature
    data:
      entity_id: climate.thermofloor_as_heatit_thermostat_tf_056_mode
      temperature: 19
