# Kichen heater off
alias: Kichen heating off
trigger:
  - platform: time
    at: '00:00:00'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_mode
      temperature: 12
  - delay: '00:00:03'
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.qubino_goap_zmnhidx_flush_on_off_thermostat_h1s2p1_mode
      hvac_mode: 'off'
