# Kichen heater off
alias: Kichen heating off
trigger:
  - platform: time
    at: '00:00:00'
action:
  - service: climate.set_temperature
    data:
      entity_id: climate.kitchen_thermostat
      temperature: 12
  - delay: '00:00:03'
  - service: climate.set_hvac_mode
    data:
      entity_id: climate.kitchen_thermostat
      hvac_mode: 'off'
